name: Quality Gate

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements-test.txt
    
    - name: Validate contracts
      run: |
        python scripts/quality/validate_contracts.py
    
    - name: Check ownership compliance
      run: |
        python scripts/quality/check_ownership.py
    
    - name: Run smoke tests
      run: |
        bash scripts/run_smoke_checks.sh
    
    - name: Gate decision
      run: |
        echo "All quality gates passed"
