name: Replay Determinism Gate

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  replay-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements-test.txt

    - name: Run replay determinism tests
      run: |
        python -m pytest tests/replay/ -v --tb=short

    - name: Verify snapshot fixtures
      run: |
        python scripts/quality/run_replay_tests.py --verify-fixtures
